name: Simple CI/CD

on:
  push:
    branches: [ master ]

jobs:
  simple-checks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install packages
      run: npm install
      
    - name: Check for errors
      run: |
        echo "✅ Code downloaded successfully"
        echo "✅ Dependencies installed"
        echo "✅  Checks completed"