import { StyleSheet, Dimensions, Platform } from "react-native";

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#E8F5E9",
    paddingTop: Platform.OS === 'android' ? 30 : 0,
  },
  
  container: {
    flex: 1,
    backgroundColor: "#E8F5E9",
  },

  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 16,
    backgroundColor: "#E8F5E9",
  }, 
  headerLogo: {
    width: 70,
    height: 70,
    borderRadius: 14,
    overflow: 'hidden'
  },
  notificationIconContainer: {
    position: 'relative',
    padding: 8,
  },
  notificationBadge: {
    position: "absolute",
    top: 4,
    right: 4,
    backgroundColor: "#EF4444",
    borderRadius: 12,
    minWidth: 22,
    height: 22,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 6,
    borderWidth: 2.5,
    borderColor: "#E8F5E9",
  },
  notificationBadgeText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "700",
  },

  welcomeSection: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 24,
    backgroundColor: "#E8F5E9",
  },
  welcomeTitle: {
    fontSize: 28,
    fontWeight: "800",
    color: "#1B5E20",
    lineHeight: 36,
    marginBottom: 12,
    lineHeight: 37,
    letterSpacing: 0.9,
  },
  studentInfoContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  studentIcon: {
    marginRight: 6,
  },
  welcomeSubtitle: {
    position: "relative",
    left: 5,
    fontSize: 16,
    color: "#252628ff",
    fontWeight: "400",
    letterSpacing: 0.4,
  },

  appointmentsContainer: {
    flex: 1,
    backgroundColor: "#fff",
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingTop: 28,
    marginTop: 4,
  },
  appointmentsList: {
    flex: 1,
    paddingHorizontal: 20,
  },
  appointmentsListContent: {
    paddingBottom: 180,
  },

  assessmentButton: {
    backgroundColor: "#FFFBEB",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#FEF3C7",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  assessmentButtonContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  assessmentButtonText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#334155",
    letterSpacing: 0.2,
  },

  appointmentCard: {
    backgroundColor: "#F8FFFE",
    borderRadius: 16,
    padding: 18,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#D1FAE5",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 16,
  },
  typeContainer: {
    flex: 1,
    marginRight: 12,
  },
  appointmentType: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1E293B",
    letterSpacing: 0.2,
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: "#3B82F620",
  },
  statusText: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.3,
    color: "#3B82F6",
  },
  cardBody: {
    gap: 12,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  infoValue: {
    fontSize: 14,
    color: "#475569",
    fontWeight: "500",
    lineHeight: 20,
    marginLeft: 8,
  },

  bookButtonContainer: {
    position: "absolute",
    bottom: 88,
    left: 0,
    right: 0,
    backgroundColor: "transparent",
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  bookButton: {
    position: "relative",
    bottom: 20,
    backgroundColor: "#48BB78",
    borderRadius: 9,
    paddingVertical: 18,
    paddingHorizontal: 24,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    shadowColor: "#48BB78",
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 8,
  },
  bookButtonIcon: {
    marginRight: 8,
  },
  bookButtonText: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "700",
    letterSpacing: 0.5,
  },

  navBar: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    backgroundColor: "#fff",
    paddingVertical: 12,
    paddingBottom: Platform.OS === 'ios' ? 20 : 16,
    position: "absolute",
    bottom: 0,
    width: "100%",
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: -4,
    },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 12,
  },
  navItem: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    paddingHorizontal: 16,
    minWidth: 70,
  },
  navLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "#64748B",
    marginTop: 5,
    letterSpacing: 0.3,
  },
  navLabelActive: {
    color: "#48BB78",
    fontWeight: "700",
  },

  centerContent: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 40,
    paddingTop: 60,
  },
  emptyAppointmentsContainer: {
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 60,
    paddingHorizontal: 40,
  },
  emptyIconContainer: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "#F1F5F9",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#334155",
    marginBottom: 8,
    textAlign: "center",
  },
  emptySubtitle: {
    fontSize: 15,
    color: "#64748B",
    fontWeight: "500",
    textAlign: "center",
    lineHeight: 22,
  },
  loadingText: {
    marginTop: 16,
    color: "#64748B",
    fontSize: 15,
    fontWeight: "600",
  },
});