import { StyleSheet, Platform } from "react-native";

export default StyleSheet.create({
  modalContainer: {
    flex: 1,
    backgroundColor: "#F8FAFC",
  },

  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: Platform.OS === "android" ? 40 : 60,
    paddingBottom: 20,
    backgroundColor: "#E8F5E9",
    borderBottomWidth: 1,
    borderBottomColor: "#D1FAE5",
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: "#1B5E20",
    letterSpacing: 0.5,
  },
  closeButton: {
    padding: 4,
  },

  tabContainer: {
    flexDirection: "row",
    backgroundColor: "#E8F5E9",
    paddingHorizontal: 20,
    paddingBottom: 16,
  },
  tab: {
    flex: 1,
    paddingVertical: 12,
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: 12,
    marginHorizontal: 4,
  },
  tabActive: {
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  tabText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#64748B",
    letterSpacing: 0.3,
  },
  tabTextActive: {
    color: "#48BB78",
    fontWeight: "700",
  },

  questionsContainer: {
    flex: 1,
  },
  questionsContent: {
    padding: 20,
    paddingBottom: 40,
  },
  questionCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  questionCardHeader: {
    flexDirection: "row",
    alignItems: "center",
  },
  questionIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#DCFCE7",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  questionCardInfo: {
    flex: 1,
    marginRight: 8,
  },
  questionCardTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: "#1E293B",
    marginBottom: 4,
    letterSpacing: 0.2,
  },
  questionCardMeta: {
    fontSize: 12,
    color: "#64748B",
    fontWeight: "500",
  },

  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 80,
    paddingHorizontal: 40,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#334155",
    marginTop: 16,
    marginBottom: 8,
    textAlign: "center",
  },
  emptySubtitle: {
    fontSize: 14,
    color: "#64748B",
    textAlign: "center",
    lineHeight: 20,
    fontWeight: "500",
  },

  answerContainer: {
    flex: 1,
    backgroundColor: "#F8FAFC",
  },
  answerHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: Platform.OS === "android" ? 40 : 60,
    paddingBottom: 20,
    backgroundColor: "#E8F5E9",
    borderBottomWidth: 1,
    borderBottomColor: "#D1FAE5",
  },
  backButton: {
    marginRight: 12,
    padding: 4,
  },
  answerHeaderTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1B5E20",
    letterSpacing: 0.3,
  },
  answerContent: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  questionDetailCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  questionDetailLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: "#48BB78",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 8,
  },
  questionDetailText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1E293B",
    lineHeight: 24,
    marginBottom: 16,
  },
  questionDetailMeta: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  questionDetailMetaText: {
    fontSize: 13,
    color: "#64748B",
    marginLeft: 6,
    fontWeight: "500",
  },

  answerInputContainer: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  answerInputLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: "#334155",
    marginBottom: 12,
    letterSpacing: 0.3,
  },
  answerInput: {
    backgroundColor: "#F8FAFC",
    borderRadius: 12,
    padding: 16,
    fontSize: 15,
    color: "#1E293B",
    minHeight: 160,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    fontWeight: "500",
    lineHeight: 22,
  },
  answerInputDisabled: {
    backgroundColor: "#F1F5F9",
    color: "#64748B",
  },
  answerInputHint: {
    fontSize: 12,
    color: "#64748B",
    marginTop: 8,
    fontStyle: "italic",
    fontWeight: "500",
  },

  answerActions: {
    flexDirection: "row",
    paddingHorizontal: 20,
    paddingVertical: 20,
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: -2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 5,
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 16,
    borderRadius: 12,
    backgroundColor: "#F1F5F9",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  cancelButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#475569",
    letterSpacing: 0.3,
  },
  submitButton: {
    flex: 2,
    paddingVertical: 16,
    borderRadius: 12,
    backgroundColor: "#48BB78",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#48BB78",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  submitButtonDisabled: {
    backgroundColor: "#94A3B8",
  },
  submitButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#fff",
    marginLeft: 8,
    letterSpacing: 0.3,
  },
});